module.exports = {
  site: {
    title: "Neel Hiro - Software Engineer",
    shortTitle: "Neel Hiro",
    description: "Software Engineer Website",
    keywords: "software engineer, software, engineer, developer, dev",
    url: "https://neelhiro.com",
    prefix: "/",
    language: "en_US",
  },
  manifest: {
    name: "Neel Hiro - Software Engineer",
    shortName: "Neel Hiro",
    startUrl: "/",
    backgroundColor: "#000000",
    themeColor: "#555555",
    display: "standalone",
  },
  socialMedia: [
    // { name: "Facebook", url: "#", color: "#3b5998" },
    {
      name: "Google",
      url: "#",
      color: "#4285f4",
      username: "google@gmail.com",
    },
    {
      name: "Twitter",
      url: "#",
      color: "#1da1f2",
      username: "@twitter",
    },
    {
      name: "Linkedin",
      url: "#",
      color: "#405de6",
      username: "linkedin.com/microsoft",
    },
    {
      name: "Github",
      url: "#",
      color: "#4078c0",
      username: "github.com/microsoft",
    },
    {
      name: "Codepen",
      url: "#",
      color: "#0ebeff",
      username: "codepen.com/dev",
    },
  ],
  navLinks: [
    {
      name: "About",
      url: "#about",
    },
    {
      name: "Projects",
      url: "#projects",
    },
    {
      name: "Contact",
      url: "#contact",
    },
  ],
  statusLinks: [
    { name: "React", url: "#" },
    { name: "GatsbyJS", url: "#" },
    { name: "Netlify", url: "#" },
  ],
  srConfig: (delay = 200) => ({
    origin: "bottom",
    distance: "50px",
    rotate: { x: 0, y: 0, z: 0 },
    delay,
    useDelay: "always",
    duration: 600,
    opacity: 0,
    scale: 1,
    easing: "ease-in-out",
    desktop: true,
    mobile: true,
    reset: false,
    viewFactor: 0.4,
    viewOffset: { top: 0, right: 0, bottom: 0, left: 0 },
  }),
}
